BoxLayout:
    orientation: 'vertical'

    BoxLayout:
        orientation: 'horizontal'

        TextInput:
            font_size: 25

        BoxLayout:
            orientation: 'vertical'
            size_hint_x: 0.25

            Button:
                text: 'Up'

            Button:
                text: 'Down'

    Button:
        text: 'Convert miles to km'
        font_size: 25

    Label:
        text: 'test'
        font_size: 25
        color: (1, 1, 0, 1)